<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" ignored="0" total="16" passed="16">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="252" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="252" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
      <class name="com.nuance.him.service.CustomerServiceImplTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.CustomerServiceImplTest@458ad742]" name="setUp" is-config="true" duration-ms="7" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testAddCustomer()[pri:0, instance:com.nuance.him.service.CustomerServiceImplTest@458ad742]" name="testAddCustomer" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddCustomer -->
        <test-method status="PASS" signature="testAddCustomerException()[pri:0, instance:com.nuance.him.service.CustomerServiceImplTest@458ad742]" name="testAddCustomerException" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <exception class="com.nuance.him.service.serviceexception.CustomerServiceException">
            <full-stacktrace>
              <![CDATA[com.nuance.him.service.serviceexception.CustomerServiceException: 
at com.nuance.him.service.customer.CustomerServiceImpl.addCustomer(CustomerServiceImpl.java:35)
at com.nuance.him.service.CustomerServiceImplTest.testAddCustomerException(CustomerServiceImplTest.java:72)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.CustomerDaoException: 
]]>
            </full-stacktrace>
          </exception> <!-- com.nuance.him.service.serviceexception.CustomerServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAddCustomerException -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.CustomerServiceImplTest@458ad742]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.CustomerServiceImplTest@458ad742]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testDisplayCustomer()[pri:0, instance:com.nuance.him.service.CustomerServiceImplTest@458ad742]" name="testDisplayCustomer" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDisplayCustomer -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.CustomerServiceImplTest@458ad742]" name="setUp" is-config="true" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testDisplayCustomerException()[pri:0, instance:com.nuance.him.service.CustomerServiceImplTest@458ad742]" name="testDisplayCustomerException" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <exception class="com.nuance.him.service.serviceexception.CustomerServiceException">
            <full-stacktrace>
              <![CDATA[com.nuance.him.service.serviceexception.CustomerServiceException: 
at com.nuance.him.service.customer.CustomerServiceImpl.getAllCustomers(CustomerServiceImpl.java:45)
at com.nuance.him.service.CustomerServiceImplTest.testDisplayCustomerException(CustomerServiceImplTest.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.CustomerDaoException: 
]]>
            </full-stacktrace>
          </exception> <!-- com.nuance.him.service.serviceexception.CustomerServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDisplayCustomerException -->
      </class> <!-- com.nuance.him.service.CustomerServiceImplTest -->
      <class name="com.nuance.him.service.AccountServiceImplTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="setUp" is-config="true" duration-ms="145" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testDepositException()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="testDepositException" duration-ms="24" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <exception class="com.nuance.him.service.serviceexception.AccountServiceException">
            <full-stacktrace>
              <![CDATA[com.nuance.him.service.serviceexception.AccountServiceException: 
at com.nuance.him.service.account.AccountServiceImpl.depositeAmount(AccountServiceImpl.java:45)
at com.nuance.him.service.AccountServiceImplTest.testDepositException(AccountServiceImplTest.java:135)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
]]>
            </full-stacktrace>
          </exception> <!-- com.nuance.him.service.serviceexception.AccountServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDepositException -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="setUp" is-config="true" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testDeposite()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="testDeposite" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeposite -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetAccountDetail()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="testGetAccountDetail" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetAccountDetail -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="setUp" is-config="true" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetAccountDetailException()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="testGetAccountDetailException" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <exception class="com.nuance.him.service.serviceexception.AccountServiceException">
            <full-stacktrace>
              <![CDATA[com.nuance.him.service.serviceexception.AccountServiceException: 
at com.nuance.him.service.account.AccountServiceImpl.getAccountDetail(AccountServiceImpl.java:65)
at com.nuance.him.service.AccountServiceImplTest.testGetAccountDetailException(AccountServiceImplTest.java:166)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
]]>
            </full-stacktrace>
          </exception> <!-- com.nuance.him.service.serviceexception.AccountServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetAccountDetailException -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetBalance()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="testGetBalance" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetBalance -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testGetBalanceException()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="testGetBalanceException" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <exception class="com.nuance.him.service.serviceexception.AccountServiceException">
            <full-stacktrace>
              <![CDATA[com.nuance.him.service.serviceexception.AccountServiceException: 
at com.nuance.him.service.account.AccountServiceImpl.getCurrentBalance(AccountServiceImpl.java:55)
at com.nuance.him.service.AccountServiceImplTest.testGetBalanceException(AccountServiceImplTest.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
]]>
            </full-stacktrace>
          </exception> <!-- com.nuance.him.service.serviceexception.AccountServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetBalanceException -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testOpenAccount()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="testOpenAccount" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOpenAccount -->
        <test-method status="PASS" signature="testOpenAccountException()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="testOpenAccountException" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <exception class="com.nuance.him.service.serviceexception.AccountServiceException">
            <full-stacktrace>
              <![CDATA[com.nuance.him.service.serviceexception.AccountServiceException: 
at com.nuance.him.service.account.AccountServiceImpl.addAccount(AccountServiceImpl.java:35)
at com.nuance.him.service.AccountServiceImplTest.testOpenAccountException(AccountServiceImplTest.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.AccountDaoException: 
]]>
            </full-stacktrace>
          </exception> <!-- com.nuance.him.service.serviceexception.AccountServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testOpenAccountException -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.AccountServiceImplTest@2344fc66]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- com.nuance.him.service.AccountServiceImplTest -->
      <class name="com.nuance.him.service.TransferAmountServiceImplTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.TransferAmountServiceImplTest@5afa04c]" name="setUp" is-config="true" duration-ms="13" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testTransactionHistory()[pri:0, instance:com.nuance.him.service.TransferAmountServiceImplTest@5afa04c]" name="testTransactionHistory" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionHistory -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.TransferAmountServiceImplTest@5afa04c]" name="setUp" is-config="true" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testTransactionHistoryException()[pri:0, instance:com.nuance.him.service.TransferAmountServiceImplTest@5afa04c]" name="testTransactionHistoryException" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <exception class="com.nuance.him.service.serviceexception.TransferAmountServiceException">
            <full-stacktrace>
              <![CDATA[com.nuance.him.service.serviceexception.TransferAmountServiceException: 
at com.nuance.him.service.transaction.TransferAmountServiceImpl.getTransactionHistory(TransferAmountServiceImpl.java:64)
at com.nuance.him.service.TransferAmountServiceImplTest.testTransactionHistoryException(TransferAmountServiceImplTest.java:107)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.TransferDaoException: 
]]>
            </full-stacktrace>
          </exception> <!-- com.nuance.him.service.serviceexception.TransferAmountServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransactionHistoryException -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.TransferAmountServiceImplTest@5afa04c]" name="setUp" is-config="true" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testTransferAmount()[pri:0, instance:com.nuance.him.service.TransferAmountServiceImplTest@5afa04c]" name="testTransferAmount" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransferAmount -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nuance.him.service.TransferAmountServiceImplTest@5afa04c]" name="setUp" is-config="true" duration-ms="1" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testTransferAmountException()[pri:0, instance:com.nuance.him.service.TransferAmountServiceImplTest@5afa04c]" name="testTransferAmountException" duration-ms="0" started-at="2019-01-17T19:32:37 IST" finished-at="2019-01-17T19:32:37 IST">
          <exception class="com.nuance.him.service.serviceexception.TransferAmountServiceException">
            <full-stacktrace>
              <![CDATA[com.nuance.him.service.serviceexception.TransferAmountServiceException: 
at com.nuance.him.service.transaction.TransferAmountServiceImpl.transferAmount(TransferAmountServiceImpl.java:54)
at com.nuance.him.service.TransferAmountServiceImplTest.testTransferAmountException(TransferAmountServiceImplTest.java:76)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:570)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:170)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:790)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:143)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at org.testng.TestRunner.privateRun(TestRunner.java:763)
at org.testng.TestRunner.run(TestRunner.java:594)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1146)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:115)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:205)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:108)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
Caused by: com.nuance.him.dao.daoexception.TransferDaoException: 
]]>
            </full-stacktrace>
          </exception> <!-- com.nuance.him.service.serviceexception.TransferAmountServiceException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testTransferAmountException -->
      </class> <!-- com.nuance.him.service.TransferAmountServiceImplTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
